const items = [
  { name: 'AC', value: 'AC' },
  { name: 'C', value: 'C' },
  { name: '%', value: '%' },
  { name: 'delete', value: 'delete', icon: 'fa-solid fa-delete-left' },
  { name: '^', value: '^' },
  { name: '(', value: '(' },
  { name: ')', value: ')' },
  { name: '/', value: '/', icon: 'fa-solid fa-divide' },
  { name: '7', value: '7' },
  { name: '8', value: '8' },
  { name: '9', value: '9' },
  { name: '*', value: '*', icon: 'fa-solid fa-xmark' },
  { name: '4', value: '4' },
  { name: '5', value: '5' },
  { name: '6', value: '6' },
  { name: '-', value: '-', icon: 'fa-solid fa-minus' },
  { name: '1', value: '1' },
  { name: '2', value: '2' },
  { name: '3', value: '3' },
  { name: '+', value: '+', icon: 'fa-solid fa-plus' },
  { name: '0', value: '0' },
  { name: '00', value: '0' },
  { name: '.', value: '.' },
  { name: '=', value: '=' },
];

export default items;